version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: sentinel-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: sentinel-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jobmanager:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sentinel-jobmanager
    ports:
      - "8081:8081"
      - "8080:8080"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    volumes:
      - ./config:/opt/flink/conf/stream-sentinel
    depends_on:
      - kafka

  taskmanager:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: sentinel-taskmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./config:/opt/flink/conf/stream-sentinel
    depends_on:
      - jobmanager

  api-gateway:
    build:
      context: .
      dockerfile: docker/api-gateway.Dockerfile
    container_name: sentinel-api-gateway
    ports:
      - "3001:3001"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_ALERT_TOPIC: alerts
      PORT: 3001
      RULES_CONFIG_PATH: /app/config/rules.yml
    volumes:
      - ./config/rules.yml:/app/config/rules.yml
    depends_on:
      - kafka

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: sentinel-frontend
    ports:
      - "80:80"
    depends_on:
      - api-gateway

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: sentinel-prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:10.0.3
    container_name: sentinel-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin_change_me}
    depends_on:
      - prometheus
